name: Windows On Codespaces Monster
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Windows Container
      run: |
        curl -sLk https://raw.githubusercontent.com/dockur/windows/master/codespaces.sh | bash -s -- 2Xww87Z4qHEK6VhbM03MWJ07X30_2fFgXbseNr7DjRyFEpSVZ
